<?php

namespace AppBundle\Repository;

/**
 * AnOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
