<?php

namespace AppBundle\Repository;

/**
 * ChoiceBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoiceBasketRepository extends \Doctrine\ORM\EntityRepository
{
}
